image: python:3.12

before_script:
  - pip install pytest mkdocs mkdocstrings[python] mkdocs-material pre-commit
  - pip install .

pre-commit:
  stage: test
  script:
    - pre-commit run --all-files

test:
  stage: test
  script:
    - pytest -v

pages:
  stage: deploy
  script:
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
