image: python:latest

before_script:
  - pip install mkdocs mkdocstrings[python] mkdocs-material
  - pip install .
pages:
  script:
    - mkdocs build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
