image: python:latest

before_script:
  - pip install pytest mkdocs mkdocstrings[python] mkdocs-material
  - pip install .

test:
  stage: test
  script:
    - pytest -v

pages:
  stage: deploy
  script:
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
