# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: "4.5.1"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # pragma: allowlist secret
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^.*\.svg
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--pytest-test-first]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 6b63472e72e1a91ed8a2f6d483790dfb644fa1d3 # pragma: allowlist secret
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/Yelp/detect-secrets
    rev: 5e141933554a0b74e7341841f318be21e895339c # pragma: allowlist secret
    hooks:
      - id: detect-secrets
  - repo: https://github.com/crate-ci/typos
    rev: 8a48f81b6c64dcfea44b3633223084c4be58ac5f # pragma: allowlist secret
    hooks:
      - id: typos
        args:
          - --config=.typos.toml
        exclude: ^.*\.svg
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: aab412d509121cb5f7533134b7e67f9fab59c682 # pragma: allowlist secret
    hooks:
      - id: ruff-format
      - id: ruff
        args: [ --fix ]
