site_name: My Docs
site_url: https://dunloplab.gitlab.io/dense-arrays
site_dir: public

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

markdown_extensions:
  - pymdownx.superfences
