site_name: Dense Arrays
site_url: https://dunloplab.gitlab.io/dense-arrays
site_dir: public
repo_url: https://gitlab.com/dunloplab/dense-arrays

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

markdown_extensions:
  - pymdownx.superfences
